# uploads all the artifacts generated by maven surefire to amazon s3 storage based on travis build number
aws s3 sync s3://test-report-allure/$TRAVIS_BUILD_NUMBER reports/$TRAVIS_BUILD_NUMBER

# change directory and list all artifacts in reports folder
cd reports/$TRAVIS_BUILD_NUMBER
export ARTIFACTS_LIST=$(ls)

# print out list of artifacts
echo $ARTIFACTS_LIST

# allure generates report after clear list of artifacts and set output directory in S3 based on travis build number
allure generate -c $ARTIFACTS_LIST -o allure/$TRAVIS_BUILD_NUMBER

# upload and aggregate one single allure report to amazon s3 storage, in the final-report folder,
# which will contain all test suites results
aws s3 sync  allure/$TRAVIS_BUILD_NUMBER s3://test-report-allure/final-report/$TRAVIS_BUILD_NUMBER
