<#include "../component.head.inc">
<#include "../form/form.get.head.ftl">
<!-- Generic Form Tool -->
<@link rel="stylesheet" type="text/css" href="${page.url.context}/res/components/console/generic-form-tool.css" />
<@script type="text/javascript" src="${page.url.context}/res/components/console/consoletool.js"></@script>
<@script type="text/javascript" src="${page.url.context}/res/components/console/generic-form-tool.js"></@script>