/*
 * Copyright (C) 2005-2009 Alfresco Software Limited.
 *
 * This file is part of the Spring Surf Extension project.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.extensions.directives;

import java.io.IOException;
import java.io.StringWriter;
import java.util.Map;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.extensions.surf.DependencyAggregator;
import org.springframework.extensions.surf.extensibility.DeferredContentTargetModelElement;
import org.springframework.extensions.surf.extensibility.ExtensibilityDirectiveData;
import org.springframework.extensions.surf.extensibility.ExtensibilityModel;

import freemarker.core.Environment;
import freemarker.template.TemplateDirectiveBody;
import freemarker.template.TemplateException;
import freemarker.template.TemplateModelException;

/**
 * <p>This FreeMarker directive should be used to add raw JavaScript. As well as ensuring that the correct script blocks are output
 * it also allows JavaScript to be relocated to other locations within the {@link ExtensibilityModel} via the {@link RelocateJavaScriptOutputDirective}
 * which enables WebScripts to ensure that all JavaScript appears at the end of an HTML page as is recommended for optimum performance.
 * It also ensures that raw JavaScript inserts are placed correctly within aggregated JavaScript resource files (generated by the 
 * {@link DependencyAggregator} service) via the group attribute.</p>
 * 
 * @author David Draper
 */
public class AddInlineJavaScriptDirective extends JavaScriptDependencyDirective
{
    private static final Log logger = LogFactory.getLog(AddInlineJavaScriptDirective.class);
    
    public AddInlineJavaScriptDirective(String directiveName, ExtensibilityModel model)
    {
        super(directiveName, model);
    }

    /**
     * Overridden to prevent the "src" attribute not specified when running in legacy mode. 
     */
    @SuppressWarnings("rawtypes")
    @Override
    protected void addLegacyDependencyRequest(Map params) throws TemplateModelException
    {
        // No action required.
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    @Override
    public ExtensibilityDirectiveData createExtensibilityDirectiveData(String id, 
                                                                       String action, 
                                                                       String target,
                                                                       Map params, 
                                                                       TemplateDirectiveBody body, 
                                                                       Environment env) throws TemplateException
    {
        // Render the body (i.e. the actual inline JavaScript code) into a StringWriter and then use that
        // along with the inline marker to construct a fake dependency. This should 
        StringWriter o = new StringWriter();
        try
        {
            body.render(o);
        }
        catch (IOException e)
        {
            // Hopefully we shouldn't have a problem rendering the body. It's unlikely we'd have made it this
            // far if we would. But we will generate an error just in case...
            logger.error("The following exception occurred processing the body of an inline JavaScript request: ", e);
        }
        
        String dependency = DependencyAggregator.INLINE_AGGREGATION_MARKER + o.toString(); 
        
        // Get the group;
        String group = getStringProperty(params, DirectiveConstants.GROUP_PARAM, false); // null is acceptable as a group (it is effectively the default group)
            
        DeferredContentTargetModelElement targetElement = getModel().getDeferredContent(OutputJavaScriptDirective.OUTPUT_DEPENDENCY_DIRECTIVE_ID, OutputJavaScriptDirective.OUTPUT_JS_DEPENDENCIES_DIRECTIVE_NAME);
        DependencyDirectiveData directiveData = new DependencyDirectiveData(id, 
                                                                            action, 
                                                                            target, 
                                                                            getDirectiveName(), 
                                                                            body, 
                                                                            env, 
                                                                            dependency, 
                                                                            group,
                                                                            getWebFrameworkConfig().isAggregateDependenciesEnabled(),
                                                                            targetElement);
        return directiveData;
    }
}
